skip_global_compinit=1

  if ! pwd &>/dev/null; then
      cd ~ 2>/dev/null || cd / 2>/dev/null
  fi


source ~/.zim/init.zsh
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/vim.zsh

# Disable AUTO_CD to prevent directory names from being treated as cd commands
unsetopt AUTO_CD
